name: Sincronizacion Aula Virtual UNAP

on:
  schedule:
    # Este cron se ejecuta todos los días, cada 2 horas.
    # (Ojo: Los servidores de GitHub usan hora UTC)
    - cron: '0 */2 * * *'
  workflow_dispatch: # Esto te permite activar el script manualmente desde la web de GitHub cuando quieras

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cambiar al código del repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-python: '3.10'

    - name: Instala las librerías necesarias
      run: |
        python -m pip install --upgrade pip
        pip install requests msal browser_cookie3

    - name: Ejecutar el Script de Sincronización
      env:
        # Aquí mapeamos la cookie que guardaste en los Repository Secrets
        AULA_VIRTUAL_COOKIE: ${{ secrets.AULA_VIRTUAL_COOKIE }}
      run: python tu_script.py # <-- CAMBIA ESTO por el nombre real de tu archivo .py