name: Sincronizacion Aula Virtual UNAP

on:
  schedule:
    # Se ejecuta cada 2 horas automáticamente (Hora UTC)
    - cron: '0 */2 * * *'
  workflow_dispatch: # Activa el botón manual en la web

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cambiar al código del repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instala las librerías necesarias
      run: |
        python -m pip install --upgrade pip
        pip install requests msal browser_cookie3

    - name: Ejecutar Sincronización Completa
      env:
        MICROSOFT_REFRESH_TOKEN: ${{ secrets.MICROSOFT_REFRESH_TOKEN }}
        UNAP_USUARIO: ${{ secrets.UNAP_USUARIO }}
        UNAP_PASSWORD: ${{ secrets.UNAP_PASSWORD }}
      run: python main.py